stages:
  - 'build'
  - 'push'

variables:
  DOCKER_HOST: 'tcp://dockerd:2376'
  DOCKER_TLS_SAN: 'DNS:dockerd'
  DOCKER_TLS_CERTDIR: '/certs'
  DOCKER_DRIVER: 'overlay2'

default:
  image: 'docker.io/docker:latest'
  services:
    - name: 'docker.io/docker:dind'
      alias: 'dockerd'

.anchors:
  - &cmd_install_packages 'apk add --no-cache coreutils git make zstd'
  - &cmd_docker_login_registry 'docker login -u "${CI_REGISTRY_USER:?}" -p "${CI_REGISTRY_PASSWORD:?}" "${CI_REGISTRY:?}"'
  - &regex_version '/^v[0-9]+$/'

build:
  stage: 'build'
  before_script:
    - *cmd_install_packages
  script:
    - 'make IMAGE_BUILD_OPTS="--pull" build-image save-image'
  artifacts:
    expire_in: '1 day'
    paths:
      - './dist/'

push:
  stage: 'push'
  needs: ['build']
  only: [*regex_version]
  before_script:
    - *cmd_install_packages
    - *cmd_docker_login_registry
  script:
    - 'make load-image push-image'
